### ISSUE TITLE
Specifying finder in $paginate does not work.

### ISSUE THREAD

**Issue by AndersTrier** [FriendsOfCake/crud#307] opened 2015-07-22 11:39 UTC
According to:
http://book.cakephp.org/3.0/en/controllers/components/pagination.html#using-controller-paginate
it should be possible to specify a finder in the $paginate array. But this does currently not result in the intended behavior.

A workaround I found is to do:
$event->subject()->query->find('someFinder', $options);
in beforePaginate.

**Comment by bravo-kernel** [comment] 2015-07-22 11:45
Thanks for creating the issue @AndersTrier

**Comment by ADmad** [comment] 2015-07-22 12:04
Would you like to make a PR fixing the issue?

**Comment by michelpeters** [comment] 2015-07-31 21:31
Ok. I've spend some time to reproduce the bug and I think I am able to confirm that Crud is ignoring the custom finder. Just a freshly baked CakePHP3 + Crud (latest) with Posts model/template/controller. The PostsController contains $paginate with ['finder' => 'somefinder']. Whatever I do in the finder, has no effect on the results from Crud on the index. 

I think the problem is in line https://github.com/FriendsOfCake/crud/blob/master/src/Action/IndexAction.php#L49 , where:

```php
  $query = $this->_table()->find();
        $subject = $this->_subject(['success' => true, 'query' => $query]);
        $this->_trigger('beforePaginate', $subject);
        $items = $this->_controller()->paginate($subject->query);
```

So, i guess because the $query object is made with `$this->_table()->find()`, it does not copy the finder/is using the finder in the later code, where `$this->_controller()->paginate($subject->query)` seems to forget about the finder specified in the $paginate array. I've tested it as data in $paginate as controller var, also within Crud's beforePaginate event. 

I'm pretty sure, the `->_table()->find()` is used because it's the "base" query for all to come after it. I'm not sure (but I bet you guys know it), but I find it weird that `paginate($subject->query)` does not get the parameters from $paginate ( but only some ). 

I'll try to track it down, before I fall asleep :)

**Comment by bravo-kernel** [comment] 2015-07-31 21:37
:+1:

**Comment by michelpeters** [comment] 2015-07-31 21:45
I've debugged some more.. I dont get the correct results, even using this code:

```php
$posts = $this->Posts->find();
$this->set('posts', $this->paginate($posts));
```

where controller's $paginate is:
```php
public $paginate = [ 
		'limit' => 25,
		'finder' => 'recent' 
];
```

I would expect that it uses my custom finder 'recent' with paginate (as noted here: http://book.cakephp.org/3.0/en/controllers/components/pagination.html#using-controller-paginate), but it does not appear to be the case. Debugging the controller and query in Crud, I get the correct data for $paginate with the finder, just before it calls the `_controller()->paginate($subject->query)`, but it seems that paginate() itself is not recognizing the finder.

I bet I've got tunnelvision this late into night, but I'm still not sure what is causing the bug.

**Comment by ADmad** [comment] 2015-07-31 21:46
The issue occurs because `PaginatorComponent` does not use the `finder` from options if a `Query` instance is passed as argument. https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L166

**Comment by michelpeters** [comment] 2015-07-31 21:47
Ah yes, that's what I was going for in my last paragraph. So, it's a CakePHP3 issue, not a Crud issue

**Comment by avinashjoshi** [comment] 2015-08-11 18:47
I have the same issue. I was on `CakePHP 3.0.8` + `Crud 4.0.0` & everything worked great, after a `composer update`, it started failing (custom finder was never called)!

`Updated version: CakePHP 3.0.11 + Crud 4.1.3`

I initially thought it to be a CakePHP and rolled back to `3.0.8`; that did not fix anything. So I kept CakePHP `3.0.11` and downgraded Crud to `4.0.0` and it worked.

The workaround `$event->subject()->query->find('someFinder', $options);` works perfectly!

Hope this description is helpful.

**Comment by michelpeters** [comment] 2015-08-12 12:56
In response to ADmad: my previous question: "So, it's a CakePHP3 issue, not a Crud issue. Would you still want to support it in Crud ?".

Meaning: Do we want to implement a fix for this into Crud, or should we fix it in CakePHP? Or neither?

**Comment by ADmad** [comment] 2015-08-12 14:53
The fix should be in core if at all.

**Comment by ADmad** [comment] 2015-10-31 05:43
@michelpeters This behavior is not going to change in the core. You can give it a shot allowing it in Crud though personally I am not inclined on that either.

**Comment by simkimsia** [comment] 2015-11-29 14:00
Should this be mentioned in the docs?

**Comment by ADmad** [comment] 2015-11-29 14:17
Closing as #348 would help solve this issue.

**Closed by ADmad** 2015-11-29 14:17 UTC
Labels: bug
