### ISSUE TITLE
Validation Exception: HTTP Code 412 vs 422

### ISSUE THREAD

**Issue by sean-nicholas** [FriendsOfCake/crud#337] opened 2015-10-30 17:32 UTC
Why is the HTTP code 412 (Precondition Failed) used for a validation exception and not 422 (Unprocessable Entity)?

It seems to me that 412 is for conditional headers.
>  The 412 (Precondition Failed) status code indicates that one or more
   conditions given in the request header fields evaluated to false when
   tested on the server.  This response code allows the client to place
   preconditions on the current resource state (its current
   representations and metadata) and, thus, prevent the request method
   from being applied if the target resource is in an unexpected state.
(http://tools.ietf.org/html/rfc7232#section-4.2)

And 422 for validation errors 
> The 422 (Unprocessable Entity) status code means the server
   understands the content type of the request entity (hence a
   415(Unsupported Media Type) status code is inappropriate), and the
   syntax of the request entity is correct (thus a 400 (Bad Request)
   status code is inappropriate) but was unable to process the contained
   instructions.  For example, this error condition may occur if an XML
   request body contains well-formed (i.e., syntactically correct), but
   semantically erroneous, XML instructions.
(http://tools.ietf.org/html/rfc4918#section-11.2)

**Comment by t73biz** [comment] 2015-11-10 03:57
+1 on this point

**Comment by josegonzalez** [comment] 2015-12-18 03:23
@AD7six You initially implemented the exception, care to explain? https://github.com/FriendsOfCake/crud/commit/0385e9bb8a9b2589e73330f690433acf29202b02

Personally I don't have any opinion either way, users are free to subclass/change the validation exception and configure their apps as necessary.

**Comment by bravo-kernel** [comment] 2015-12-19 09:34
:+1: on sending the "most appropriate" header by default (even though it would break my current tests).

**Comment by AD7six** [comment] 2016-02-07 15:52
:+1: to changing it to 422, it does seem more appropriate.

412 was already in use by the predecessor to crud, I don't recall finding anything that contradicted, or gave a better example, to using that response code at the time (though I do remember long discussions about what code to use).

There seems to now be precedent to use 422 e.g [json api suggests that](http://jsonapi.org/examples/):

A Basic Error Object

In the response below, the server is indicating that it encountered an error while creating/updating the resource, and that this error was caused by an invalid "first-name" attribute:

![screenshot from 2016-02-07 16-51-54](https://cloud.githubusercontent.com/assets/33387/12873357/1c0d454e-cdbb-11e5-9bda-47a37312ad50.png)

**Comment by jadb** [comment] 2016-02-11 14:20
Closing, PR #387

**Closed by jadb** 2016-02-11 14:20 UTC

**Comment by bravo-kernel** [comment] 2016-05-12 21:52
Bumped into a couple of 412 references today: https://github.com/FriendsOfCake/crud/search?utf8=%E2%9C%93&q=412. Do these require updating as well?

**Comment by josegonzalez** [comment] 2016-05-12 21:59
Sure, go for it.
