### ISSUE TITLE
deleteAction does not send code 400 on ValidationException

### ISSUE THREAD

**Issue by mcube27** [FriendsOfCake/crud#642] opened 2020-06-19 05:14 UTC
Using version 5.4.7 with cakephp 3.8

I am doing a test that should fail on deleting an entity.
It should fail because I added a rule on delete only.

When Crud deletes it, instead of sending status code 400, it returns status code 200.
If I change the api config to exception instead of code 400, it works as expected.

**Comment by ADmad** [comment] 2020-06-19 06:30
`ValidationException` uses status code `422` by default and we have test cases for the same. So if you are seeing `200` instead you need to provide a way to reproduce the issue.

**Comment by ADmad** [comment] 2020-06-19 06:38
Okay, I see that `DeleteAction` isn't configured to use `ValidationException` like add/edit action but it's still configured to use `400` code in case of error https://github.com/FriendsOfCake/crud/blob/a58c8b7862a9a27977d22559f2e0eb19ac5ee681/src/Action/DeleteAction.php#L46.

**Comment by mcube27** [comment] 2020-06-19 09:32
Note that I use the ListernerAPI.

If I change the config to ValidationException it all works as expected.

But leaving it to use `400` code does not result in a `400` response status but in a `200`.

I really just used `$this->Crud->delete()` with a `addDelete? rule in the table.

**Comment by ADmad** [comment] 2020-06-19 13:24
Okay, if you can figure out the cause of the problem then a pull request to fix the issue would be appreciated.

**Comment by ADmad** [comment] 2020-06-19 17:25
I am unable to reproduce your issue using a test case #643, hence closing.

**Closed by ADmad** 2020-06-19 17:25 UTC
Labels: needs more info
