### ISSUE TITLE
Custom finders does not work in IndexAction

### ISSUE THREAD

**Issue by Asgraf** [FriendsOfCake/crud#371] opened 2015-12-14 09:42 UTC
````php
	public function index() {
		$this->Crud->on('beforePaginate', function(Event $event) {
			$this->paginate['finder']='active';
		});
		return $this->Crud->execute();
	}
````
Table method findActive() is never called

Tested on Crud 4.2.1 & CakePHP 3.1.5

**Comment by josegonzalez** [comment] 2015-12-14 09:51
Can you try the following instead:

```php
$this->Crud->action()->findMethod('active');
```

**Comment by Asgraf** [comment] 2015-12-14 10:30
Thanks, your solution worked but it is undocumented.

http://crud.readthedocs.org/en/latest/actions/index.html#add-conditions
http://book.cakephp.org/3.0/en/controllers/components/pagination.html#using-controller-paginate
Currently documentation suggest using $this->paginate['finder'] so my approach should work too.

**Comment by bravo-kernel** [comment] 2015-12-14 11:15
Nice suggestion Mr. @josegonzalez, looks a lot cleaner :relaxed:

**Comment by ADmad** [comment] 2015-12-14 12:08
Duplicate of #307. The reason why using `finder` option for `$paginate` doesn't work is Crud first creates a `Query` instance` which is passed to `Controller::paginate()` and `PaginatorComponent::paginate()` ignores `finder` option if a `Query` instance is passed. I'll add the clarification to Crud docs.

**Closed** 2015-12-14 17:16 UTC
