### ISSUE TITLE
Cakephp 4.4 breaks ApiListener

### ISSUE THREAD

**Issue by asgraf** [FriendsOfCake/crud#676] opened 2022-06-23 08:59 UTC
In cakephp 4.4 `$this->getRequest()->is('xml')` always returns true, even for regular html requests (tested on latest Firefox).
This break ApiListener because `$this->getRequest()->is('api')` is now always true and this causes it to throw `Method Not Allowed` exception for all GET requests 

Probably bug in cakephp 4.4 it self

**Comment by ADmad** [comment] 2022-06-24 08:23
Closing as the issue isn't directly related to this plugin.

**Comment by sitedyno** [comment] 2022-07-08 18:32
Are the detectors defined by ApiListener needed? They are defined here:
https://github.com/FriendsOfCake/crud/blob/ace4262d8c1c6d4b26937cb19f8d3b1b954aeb4b/src/Listener/ApiListener.php#L36-L38

Commenting out the following lines keeps ApiListeners from overriding the CakePHP listeners and things work for me again:
https://github.com/FriendsOfCake/crud/blob/ace4262d8c1c6d4b26937cb19f8d3b1b954aeb4b/src/Listener/ApiListener.php#L392-L394

**Comment by ADmad** [comment] 2022-07-09 03:46
While the `is(xml)` and `is(json)` checks will continue working, without the overrides the custom `is(api)` check won't. So the overrides will have to be updated to include the new `exclude` key for XML as done in core.

**Closed** 2022-07-09 16:23 UTC
